SEED: 100
ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 50000

SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  AGENT_0:
    SENSORS: ["RGB_SENSOR"]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  SEMANTIC_SENSOR:
    WIDTH: 128
    HEIGHT: 128

TASK:
  TYPE: Nav-v0
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SUCCESS_DISTANCE: 1.

  SENSORS: ["IMAGEGOAL_SENSOR_V2"]
  GOAL_SENSOR_UUID: "imagegoalv2"

  MEASUREMENTS: ["DISTANCE_TO_GOAL", "SUCCESS", "SPL", "SOFT_SPL", "DISTANCE_TO_VIEW", "VIEW_MATCH", "VIEW_ANGLE"]
  SUCCESS:
    SUCCESS_DISTANCE: 1.

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/zer/imagenav/gibson/v1/{split}/{split}.json.gz
